services:
  wishnest:
    container_name: wishnest
    build: .
    ports:
      - "3002:3000"
    environment:
      # PostgreSQL Database configuration
      - DATABASE_URL=${DATABASE_URL:-postgresql://wishnest:wishnest123@postgres:5432/wishnest}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3002}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-change-this-in-production}
      # Admin bootstrap (comma-separated emails allowed)
      - ADMIN_EMAILS=${ADMIN_EMAILS:-}
      # PostgreSQL settings (needed for pg_isready command)
      - POSTGRES_DB=${POSTGRES_DB:-wishnest}
      - POSTGRES_USER=${POSTGRES_USER:-wishnest}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-wishnest123}
      # Database operation controls
      - ALLOW_PRISMA_DB_PUSH=${ALLOW_PRISMA_DB_PUSH:-false}
      - ALLOW_PRISMA_FORCE_RESET=${ALLOW_PRISMA_FORCE_RESET:-false}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-wishnest}
      - POSTGRES_USER=${POSTGRES_USER:-wishnest}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-wishnest123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 