version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wishnest-postgres
    restart: always
    environment:
      POSTGRES_USER: wishnest
      POSTGRES_PASSWORD: wishnest123
      POSTGRES_DB: wishnest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wishnest"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 